### ISSUE TITLE
Any usage instructions ?

### ISSUE THREAD

**Issue by erfanmola** [w3champions/map-updater-scripts#8]
Any tutorial or insructions on HOW TO USE this project ? This is not how an open-source project is maintained, this is just a personal project of some developer who forget to make his repo private

The updater script is in bash which means it cannot run on windows natively or at least with WSL, but the MPQ stuff is in exe which needs windows, also when we run the script it has problem with Paths and ..., it's just like it's hard-coded to work on authors device

**Comment by abeninski** [comment]
Hey,
Sorry to hear you could not run it.

I use git bash to run the script.
The rest of the instructions are in the readme.

We will work more in the future (when we have time) to up our game for documentation.
